__version__ = "1.0"

import os 
from pathlib import Path
from meshroom.core import desc
from meshroom.core.utils import DESCRIBER_TYPES

class MatchMasking(desc.CommandLineNode):

    category = "ROMA"
    documentation = """
    Mask the certainty images generated by RomaMatcher given the associated 
    masks of the reference and matched images.
    """
    size = desc.DynamicNodeSize('inputSfMData')

    parallelization = desc.Parallelization(blockSize=40)
    commandLineRange = "--rangeIteration {rangeIteration} --rangeBlocksCount {rangeBlocksCount}"
    
    exePath = (Path(__file__).absolute().parent.parent.parent / "python" / "masker.py").as_posix()
    commandLine="python "+exePath+" {allParams}"

    inputs = [
        desc.File(
            name="inputSfMData",
            label="SfMData",
            description="Input SfMData file.",
            value="",
        ),
        desc.File(
            name="imagePairsList",
            label="Image Pairs",
            description="Path to a file which contains the list of image pairs to match.",
            value="",
        ),
        desc.File(
            name="warpFolder",
            label="warp folder",
            description="",
            value=""
        ),
        desc.File(
            name="certaintyFolder",
            label="Certainty folder",
            description="",
            value=""
        ),
        desc.File(
            name="masksFolder",
            label="Masks folder",
            description="",
            value=""
        ),
        desc.ChoiceParam(
            name="masksExtension",
            label="Mask File Extension",
            description="Mask file extension",
            value="exr",
            values=["exr", "png", "jpg"],
            exclusive=True,
        )
    ]

    outputs = [
        desc.File(
            name="outputCertaintyFolder",
            label="Output Certainty folder",
            description="",
            value="{nodeCacheFolder}"
        )
    ]
