__version__ = "1.3"

import os 
from pathlib import Path
from meshroom.core import desc
from meshroom.core.utils import DESCRIBER_TYPES
from pyalicevision import parallelization as avpar

class MatchMasking(desc.CommandLineNode):

    category = "ROMA"
    documentation = """
    Mask the confidence images generated by RomaMatcher given the associated 
    masks of the reference and matched images.
    """
    size = avpar.DynamicViewsSize('inputSfMData')

    parallelization = desc.Parallelization(blockSize=40)
    commandLineRange = "--rangeIteration {rangeIteration} --rangeBlocksCount {rangeBlocksCount}"
    
    exePath = (Path(__file__).absolute().parent.parent.parent / "python" / "masker.py").as_posix()
    commandLine="python "+exePath+" {allParams}"

    inputs = [
        desc.File(
            name="inputSfMData",
            label="SfMData",
            description="Input SfMData file.",
            value="",
        ),
        desc.File(
            name="imagePairsList",
            label="Image Pairs",
            description="Path to a file which contains the list of image pairs to match.",
            value="",
        ),
        desc.File(
            name="warpFolder",
            label="warp folder",
            description="",
            value=""
        ),
        desc.File(
            name="confidenceFolder",
            label="Confidence folder",
            description="",
            value=""
        ),
        desc.ListAttribute(
            name="masksFolders",
            label="Masks folders",
            description="List of folders where mask files can be looked up.",
            elementDesc=desc.File(
                name="masksFolder",
                label="Masks folder",
                description="",
                value=""
            ),
            exposed=True
        ),
        desc.ChoiceParam(
            name="masksExtension",
            label="Mask File Extension",
            description="Mask file extension",
            value="exr",
            values=["exr", "png", "jpg"],
            exclusive=True,
        )
    ]

    outputs = [
        desc.File(
            name="outputConfidenceFolder",
            label="Output Confidence folder",
            description="",
            value="{nodeCacheFolder}"
        )
    ]
